
spring.datasource.url: jdbc:mysql://localhost:3306/socios
spring.datasource.username: socios_user
spring.datasource.password: password

spring.jpa.properties.jakarta.persistence.schema-generation.database.action: drop-and-create
